### ISSUE TITLE
Wrong class returned with all() for relationship

### ISSUE THREAD

**Issue by unidesigner** [scholrly/neo4django#115]
I have the following classes

```
from neo4django.db import models
import neo4django

class Concept(models.NodeModel):
    name = models.StringProperty(indexed=True)

class Group(Concept):    
    part_of = models.Relationship('Group',
        rel_type=neo4django.Outgoing.PART_OF,
        single=True,
        related_name='elements')

    part_of = models.Relationship('Root',
        rel_type=neo4django.Outgoing.PART_OF,
        single=True,
        related_name='elements')

class Root(Concept):
    pass

class Element(Concept):
    part_of = models.Relationship(Group,
        rel_type=neo4django.Outgoing.PART_OF,
        single=True,
        related_name='elements')

```

If I now create a series:

```

e1 = Element.objects.create(name='my element 1')
g1 = Group.objects.create(name='my group 1')
g2 = Group.objects.create(name='my group 2')
r1 = Root.objects.create(name='my root')

```

and link:

```

e1.part_of = g1
e1.save()

g1.part_of = g2
g1.save()

g2.part_of = r1
g2.save()
```

If I return now the elements of g2:

```
g2.elements.all()
```

It displays one object of type Element which should be of type Group. If I
print the name of the object and id, I get the correct information for the group, i.e. g1.

Sideremark: Is it correct how I define multiple relations e.g. for the class Group?

**Comment by mhluongo** [comment]
@unidesigner Actually, that's expected behavior. I would expect `g2.elements.all()` to return all `Element`s related to (part of) the group `g2`, since your last `part_of` relationship on `Element` points to group with a related name of `"elements"`.

In situations like this, we've kept consistent with Django conventions (as best we can). See eg https://docs.djangoproject.com/en/dev/topics/db/models/#relationships.

Could you explain your domain, and I can give you an idea of how I think the models should look? That might clear things up. Do groups contain roots and elements?

Re: multiple relationships - you can't have multiple relationships of the same name defined like that. Instead, either choose  two different names,

**Comment by unidesigner** [comment]
What I see is that `g2.elements.all()` returns correctly `g2`, but also `e1` which it should not by default. Only if I would set depth to bigger than one, it might traverse all `part_of` relationships and return objects deeper in the hierarchy.

It becomes probably more clear with the simple data model I try to map in our CATMAID software from a relational model to the graph model:
![ObjectTree](http://unidesign.ch/3dshare/objecttree.png)
A neuron can be part_of a group, but not part_of root. There is only one root (the entry point to the tree, in this case neuropiletest). Groups can be part_of other groups, or part_of the root. It's basically a tree where the leaf nodes are either groups or neurons.

Re: multiple relationships: Does this mean I can not use the same relationship name (e.g. part_of) between neuron and groups, and group and groups?

The model is here:
https://github.com/acardona/CATMAID/blob/django-user/django/applications/catmaid2/models.py

**Comment by mhluongo** [comment]
Hm, there is an issue here- neo4django infers model types by relationship type, so constructs like this are a little awkward. Problems like this crop up since neo4j doesn't have node types.

OTOH, you're trying to write model definitions outside of how the library expects them. For example, in Django, defining multiple fields that way just overwrites the prior fields, so you can't have two `part_of` definitions on the same model class.

I just [wrote a gist](https://gist.github.com/2988938) that I think might be a good approach. Let me know how it works for you.

**Comment by unidesigner** [comment]
I see, your proposed approach in the gist works for me, thanks!

What does the class Meta: abstract = True do?

**Comment by mhluongo** [comment]
Great! :) Is there anything I could do to improve the docs?

The `class Meta` bit is how Django accepts extra model-wide configs. `abstract = True` is just the Django approach to abstract classes (as opposed to Python's `abc`). Practically speaking, in neo4django, abstract classes don't get type nodes so they won't litter your in-graph type hierarchy.

**Comment by unidesigner** [comment]
The Readme file is already quite long, maybe setting up a dedicated sphinx-based site (easy with readthedocs.org) would help. I find examples always quite helpful, like the one you wrote in the gist. But then, it's always helpful to read the tests.
