### ISSUE TITLE
Getting AttributeError: type object 'Model' has no attribute '__metaclass__' when running python manage.py syncdb

### ISSUE THREAD

**Issue by drewnix** [scholrly/neo4django#149]
Trying to get a basic neo4django setup to play around with by following the instructions on this page:

https://neo4django.readthedocs.org/en/latest/getting-started.html

I'm using django-1.5.

I set the basic configuration listed on the page then attempted to run syncdb:
$ python manage.py syncdb
AttributeError: type object 'Model' has no attribute '**metaclass**'

**Comment by stephendwolff** [comment]
Funny - i had the same problem today - and reverted to Django 1.4.4 (where it doesn't happen).

I think there's already an open 'Django 1.5 Support' issue - without any comments yet.

**Comment by mhluongo** [comment]
@stephendwolff is absolutely right. I've played with supporting Django 1.5 in a private branch, but I wanted to get a few more features in before I added another version I need to test against. Now that we have auth support and a saner queryset implementation, this shouldn't be too tough. I'm closing this issue (since it's a duplicate) but you shouldn't have to wait long for 1.5 support.

**Comment by rosscdh** [comment]
Hey there! Firstly fantastic work on this awesome project. I look forward to using and contributing to it where I can.

Has there been any movement on this item? What is teh eta on 1.5 support? and do you need a hand with that deliverable?

**Comment by mhluongo** [comment]
Aw, thanks! There hasn't been much movement yet on Django 1.5 support (#143) but it's slated for next release, which I hope to have out in a month or two. I'd love help with it. Much of the work should be pretty straightforward- eg the above can be fixed by using `type(Model)` instead of `Model.__metaclass__`\- and much of it will be related to changes in Django 1.5 made to support Python 3.

The other difference I imagine might be User model related. Now that Django has configurable User models, I'm not sure how best to integrate with it- it might be as simple as including `AUTH_USER_MODEL='neo4django.auth.models.User` in settings.py.

Anyway, help would certainly be appreciated. I'm planning on working on admin support (#139) and some other query features (#146) next, so this would be a great issue to work on.

**Comment by mhluongo** [comment]
@rosscdh are you still interested in this?

**Comment by rosscdh** [comment]
Hi Matt I am but unfortunately am up to my ears at the moment.

I may have some time next week for it?

Are there any plans for it?

**Comment by mhluongo** [comment]
No, no plans- sorry, not trying to rush you. I just wanted to make sure I hadn't scared you off :)

**Comment by mhluongo** [comment]
Folks- I've started a campaign to fund the completion of this release, including [1.5+ support](https://github.com/scholrly/neo4django/issues/143). Check it out at https://www.bountysource.com/fundraisers/423-neo4django-0-1-9
