### ISSUE TITLE
Migrate from neo_auth to graph_auth

### ISSUE THREAD

**Issue by pirhoo** [scholrly/neo4django#222]
Hello,

I'm trying to migrate a database that was using the old **User** model (with _neo_auth_ app label). I took care to update the model definition directly into neo4j by changing the _app_label_ and _name_ as follows:

![capture du 2013-10-23 17 03 37](https://f.cloud.github.com/assets/471176/1390881/5d684bca-3bf4-11e3-8823-1d8e16c5f91e.png)

When I try to get the list with _User.objects.all()_ it works as expected. But when I try to get a single node using get (i.e. _User.objects.get(username='pirhoo')_) it throws a not found error.

Any idea ?

All the best,
Pierre

**Comment by tonjo** [comment]
When you change a model is a pain. Sometimes adding a single field in the model definition
will cause things like yours. Try recreating the model with `create`, copying fields from the old one.
Sometimes I had to destroy and recreate the reference node, starting with a clean db
(in early developement stage).

PS: Did you see my pull request #217 that will fix the wrong model? I don't think it's related, anyway,
it's an `authenticate` problem.

**Comment by pirhoo** [comment]
Thanks for the quick anwser @tonjo ! 
Your pull request isn't related to my problem but I also noticed that issue :) Otherwise, I'm gonna try what you suggest.

**Comment by mhluongo** [comment]
@Pirhoo, @tonjo's advice is good. Since indexing is done via the library- not auto-indexes- you have to go through the library to properly migrate. When Neo4j 2.0 is released this will be fixed with schema indexes.

Let us know how it goes! I'd love to share any resulting code in the migrations section of the docs.

**Comment by pirhoo** [comment]
@mhluongo if the problem may come from the indexes, is there a way to reset a specified index manually?

**Comment by mhluongo** [comment]
Definitely. Basically, you could either rename the old index or reindex its contents. The library indexes using Groovy- the relevant bits are in library.groovy, around https://github.com/scholrly/neo4django/blob/master/neo4django/gremlin/library.groovy#L186. The easiest way to force a reindex might be something like

```
for u in User.objects.all():
    u.save()
```

Renaming the index might also work, but since I can't test right now I think the above attempt would be safest.

**Comment by pirhoo** [comment]
Now I can get an user and login: thanks to your tips to reindex! 
I'm going to write a Django Command to force reindex, I will post a gist here if you are interested.

Thanks!

**Comment by mhluongo** [comment]
Glad we could help.

re: the command - yes please!

## 

Matt Luongo
Software Developer
about.me/luongo

**Comment by pirhoo** [comment]
Hi again! Here is the command: https://gist.github.com/Pirhoo/7122246
