### ISSUE TITLE
cannot import name 'transactional' error

### ISSUE THREAD

**Issue by ctippur** [scholrly/neo4django#256]
Hello,

I am trying to use neo4django. I am at the getting started stage in the document:

https://neo4django.readthedocs.org/en/latest/getting-started.html

I am getting an error when I run it - cannot import name 'transactional'

Wondering if someone can shed some light on this.
I am using django 1.8.2 and python 3.4.
- Shekar

**Comment by tonjo** [comment]
I'm afraid Python 3 is not supported, as stated by the author himself in #236.
Also, I think latest Django version supported is 1.5.
Unluckily, this project is not so alive, latest release was 2 years ago.

**Comment by ctippur** [comment]
Tonjo,

Thanks for responding. 
What would be the most recommended package to use?
There are several tools explained here - http://neo4j.com/developer/python/ but not sure what to pick. I picked neo4django because it came close to the schematics of mvc framework.
- Shekar

**Comment by tonjo** [comment]
Sorry, can't help because I was working on a project that ended,
so I didn't need it anymore.
I think neo4django is the 'coolest' one, for its completeness,
see this article: http://stackoverflow.com/questions/14871775/django-and-neo4j-without-neo4django .
With `Neo4jdb-Python` I think you're forced to do cypher queries (not sure).
I kinda like `neomodel` because it's an object mapper similar to Django's ORM: http://nigelsmall.com/py2neo/1.6/neomodel/ .
Be careful with Python version, 3.3 it says in this case.

**Comment by mhluongo** [comment]
Sorry guys, we don't yet support Python 3. Closing this, but keep up with progress on #260
